### ISSUE TITLE
Add a software license?

### ISSUE THREAD

**Issue by dapetcu21** [dantreble/Tweener#1]
Hi!

We'd like to use your tweening library in our project. Can you add a software license to this repo, so that people can legally use it? I suggest something simple, like the [MIT license](https://mit-license.org/license.txt). Dropping it in a `LICENSE.md` file in the root of the project should suffice.

**Comment by dantreble** [comment]
Added one, hope that ticks the box

**Comment by dapetcu21** [comment]
Awesome, thanks!
